config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/exact_count'
  get 'home/possible_world_count'
  get 'home/possible_world_count_agg'
  get 'home/hist_count'
  get 'home/top_count'
  get 'home/algorithm'
  get 'algorithm/index'
  post 'algorithm/create'
  get 'algorithm/show'
  get 'algorithm/new'
  get 'experiment/index'
  get 'experiment/new'
  get 'experiment/show'
  get 'experiment/create'
  get 'experiment/a'
  get 'experiment/b'
  get 'experiment/c'
  get 'experiment/d'
  get 'experiment/e'
  get 'experiment/f'
  post 'dict/create'
  post 'cat_breed/create'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  default_scope { order('id desc') }

  belongs_to :algorithm
end

app/controllers/experiment_controller.rb
class ExperimentController < ApplicationController
  before_action :query_data, except: [:new,:create]
  def index
  end

  def show
  end

  def create
    Experiment.create(
      algorithm_id: params["algorithm_id"],
      result: JSON.parse(params["results"].gsub('\"', '"')),
      name: params["name"],
    )
  end

  private

  def query_data
    @results = {};
    algorithm_ids = params[:algorithm_ids] || [Algorithm.first.id]

    EXPERIMENTS.each do |experiment_name|
      @results[experiment_name] = {}
      ep = Experiment.where(algorithm_id: algorithm_ids, name: experiment_name).includes(:algorithm)

      result = ep.map do |x|
        x.result.each{ |key,str| x.result[key] = str }
        x.result = x.result.sort{|a,b| a[0].to_i<=>b[0].to_i}[0..-1].to_h
        { name: algoname[x.algorithm.name.to_sym] || x.algorithm.name, data: x.result }
      end.uniq { |s| s[:name].upcase}
      result = result.sort{|a,b| a[:name]<=>b[:name]}

      @results[experiment_name][:result] = result
      @results[experiment_name][:x_title] = chart_desc[experiment_name][:x_title]
      @chart_desc = chart_desc
      @colors = colors
    end
  end

  def chart_desc
    {
      experiment_a: {title: 'Experiment A investigates varying number of tuples', 'x_title': '# Records'},
      experiment_b: {title: 'Experiment B explores the effects of varying number of distinct variables (15 tuples)', 'x_title': '#vars'},
      experiment_c: {title: 'Experiment C investigates the effects of varying number of alternatives(5 tuples, 5 rv)', 'x_title': '#alternatives'},
      experiment_d: {title: 'Experiment D  studies the effects of varying complexity of the sentence (15 tuples)', 'x_title': 'n of arity'},
      experiment_e: {title: 'Experiment E varying the number of bins B in hist count (15 tuples)', 'x_title': 'n bins'},
      experiment_f: {title: 'Experiment F varying the number of top k in top count(15 tuples)', 'x_title': 'k'},
    }
  end

  def algoname
    {
      top_count: 'Top 5',
      comb_count: 'Combination',
      possible_world_count: 'Possible World',
    }
  end

  def colors

    c = ["#e60049", "#0bb4ff", "#50e991", "#e6d800", "#9b19f5", "#ffa300", "#dc0ab4", "#b3d4ff", "#00bfa0"]

  end
end

app/views/experiment/a.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: @title,  xtitle: @x_title, ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/b.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: 'Experiment B explores the effects of varying number of distinct variables (14 records)',  xtitle: 'number of variables', ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/c.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: 'Experiment C investigates the effects of varying number of alternatives(5 records, 5 rv)',  xtitle: 'number of alternatives', ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/d.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: 'Experiment D  studies the effects of varying complexity of the sentence(10 records, 5 rv)',  xtitle: 'number of arity', ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/e.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: 'Experiment E varying the number of bins B in approximate count (as a histogram)(8 records, 6 rv)',  xtitle: 'number of bins', ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/f.js.erb
$(".result").html("<%= j line_chart @result, discrete: true, title: 'Experiment F varying the number of top k in top count (8 records)',  xtitle: 'top k', ytitle: 'Execution time in ms',  height: '550px'%>");

app/views/experiment/index.html.slim
.container-xxl
  .col-12.px-5
    h1.my-3 Experiments
    = form_with url: experiment_show_path, method: :get, remote: true do |f|
      .row.mb-3
        .col-2
          = label_tag :algorithm_ids, 'Algorithms:', class: 'px-3'
        .col-4
          = f.select :algorithm_ids, options_from_collection_for_select(Algorithm.all, :id, :name, Algorithm.first&.id),{}, {class: 'custom-select form-control', id: 'js-algorithm-select', multiple: true  , size: 5}
        .col-6
          = f.submit 'Get Experiment Result', class: 'btn btn-dark'
    .row
      .col-12.my-2
        #accordionPanelsStayOpenA.accordion
          .accordion-item
            h2#panelsStayOpen-headingA.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_a" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_a" data-bs-toggle="collapse" type="button"
                | Experiment A
            #panelsStayOpen-collapse-experiment_a.accordion-collapse.show aria-labelledby="panelsStayOpen-headingA"
              .accordion-body
                .description style="height: 130px"
                  strong Varying number of tuples.
                  | This is to check the feasibility of the algorithm with respect to the size of the database, and also visualize the complexity of the algorithm.
                .result
      .col-12.my-2
        #accordionPanelsStayOpenB.accordion
          .accordion-item
            h2#panelsStayOpen-headingB.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_b" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_b" data-bs-toggle="collapse" type="button"
                | Experiment B
            #panelsStayOpen-collapse-experiment_b.accordion-collapse.show aria-labelledby="panelsStayOpen-headingB"
              .accordion-body
                .description style="height: 130px"
                  strong Varying number of variables.
                  | This explores the effects of varying number of distinct variables while keeping the number of records constant and the number alternatives per variable at 1. This will produce an increasingly larger sentence and the depth of the BDD tree.
                .result
      .col-12.my-2
        #accordionPanelsStayOpenC.accordion
          .accordion-item
            h2#panelsStayOpen-headingC.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_c" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_c" data-bs-toggle="collapse" type="button"
                | Experiment C
            #panelsStayOpen-collapse-experiment_c.accordion-collapse.show aria-labelledby="panelsStayOpen-headingC"
              .accordion-body
                .description style="height: 130px"
                  strong Varying Number of alternatives.
                  | This check the effects of varying number of alternatives, while keeping the number of variables constants.
                .result.mt-5
      .col-12.my-2
        #accordionPanelsStayOpenD.accordion
          .accordion-item
            h2#panelsStayOpen-headingD.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_d" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_d" data-bs-toggle="collapse" type="button"
                | Experiment D
            #panelsStayOpen-collapse-experiment_d.accordion-collapse.show aria-labelledby="panelsStayOpen-headingD"
              .accordion-body
                .description style="height: 130px"
                  strong Varying sentence complexity.
                  | It studies the effects of varying complexity of the sentence while keeping the number of variable and alternative constant. This experiment mimics the answering of increasingly complex queries in a database
                .result.mt-5
      .col-12.my-2
        #accordionPanelsStayOpenE.accordion
          .accordion-item
            h2#panelsStayOpen-headingE.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_e" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_e" data-bs-toggle="collapse" type="button"
                | Experiment E
            #panelsStayOpen-collapse-experiment_e.accordion-collapse.show aria-labelledby="panelsStayOpen-headingE"
              .accordion-body
                .description style="height: 130px"
                  strong Varying the number of bins.
                  | It discover the scale of running time on number of request bins.
                .result.mt-5
      .col-12.my-2
        #accordionPanelsStayOpenF.accordion
          .accordion-item
            h2#panelsStayOpen-headingF.accordion-header
              button.accordion-button aria-controls="panelsStayOpen-collapse-experiment_f" aria-expanded="true" data-bs-target="#panelsStayOpen-collapse-experiment_f" data-bs-toggle="collapse" type="button"
                | Experiment F
            #panelsStayOpen-collapse-experiment_f.accordion-collapse.show aria-labelledby="panelsStayOpen-headingF"
              .accordion-body
                .description style="height: 130px"
                  strong Varying top k ranking.
                  | It is varying k in approximate count (as top-k ranking) to discover the scale of running time on k.
                .result.mt-5


javascript:
  $("#js-algorithm-select").select2({
    maximumSelectionLength: 5
  })
  $(document).ready(function() {
    $('[data-bs-toggle="tooltip"]').tooltip();
  });

app/views/experiment/new.html.slim
.container-xxl
  .col-.px-5
    h1.my-3 Add Experiments data
    = form_with url: experiment_create_path, method: :get, remote: true do |f|
      = label_tag :algorithm_id, 'Algorithms:'
      = f.select :algorithm_id, options_from_collection_for_select(Algorithm.all, :id, :name),{}, {class: 'custom-select form-control input-control', id: 'js-algorithm-select'}

      = label_tag :name, 'Experiment:', class: 'mt-2'
      = f.select :name, [:experiment_a, :experiment_b, :experiment_c, :experiment_d, :experiment_e, :experiment_f],{}, {class: 'custom-select form-control input-control'}

      = label_tag :results, 'Result:', class: 'mt-2'
      = f.text_area :results, {class: 'custom-select form-control input-control'}
      .row
        .col-2.mt-2
          = f.submit 'Add experiment data', class: 'btn btn-info'

app/views/experiment/show.js.erb
<% EXPERIMENTS.each do |experiment_name| %>
  $("<%= "#panelsStayOpen-collapse-#{experiment_name} .result" %>").html("<%= j line_chart @results[experiment_name][:result], discrete: true, points: false,  suffix: "ms", xtitle:  @results[experiment_name][:x_title], height: '400px', width: '800px', colors: @colors, library: {backgroundColor: 'red'}%>");
<%end %>