config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/exact_count'
  get 'home/possible_world_count'
  get 'home/possible_world_count_agg'
  get 'home/hist_count'
  get 'home/top_count'
  get 'home/algorithm'
  get 'algorithm/index'
  post 'algorithm/create'
  get 'algorithm/show'
  get 'algorithm/new'
  get 'experiment/index'
  get 'experiment/new'
  get 'experiment/show'
  get 'experiment/create'
  get 'experiment/a'
  get 'experiment/b'
  get 'experiment/c'
  get 'experiment/d'
  get 'experiment/e'
  get 'experiment/f'
  post 'dict/create'
  post 'cat_breed/create'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dict = Dict.my_dict
    @cat_breeds = CatBreed.all_with_prob
  end

  def exact_count
    @cat_count = CatBreed.exact_count
  end

  def hist_count
    bin = params[:bin].presence || 2
    @cat_count = CatBreed.hist_count(bin)
  end

  def top_count
    k = params[:k].presence || 1
    @cat_count = CatBreed.top_5_count
  end

  def possible_world_count_agg
    @cat_count = CatBreed.count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_count_result.html.slim
.mt-4
  table.table.table-hover.table-bordered.border-black
    thead.table-dark
      th Count
      th Bdd
    - cat_count.each_with_index do |cat, index|
      tr
        td= cat['count']
        td= cat['bdd']

app/views/home/_hist_count_result.html.slim
.mt-4
  table.table.table-hover.table-bordered.border-black
    thead.table-dark
      th Count
      th Bdd
    - cat_count.each_with_index do |cat, index|
      - cat = cat['hist_count'][1..-2].split(',')
      tr
        td= cat[0][1..-2]
        td= cat[1][1..-2]

app/views/home/_possible_world_count_agg_result.html.slim
.mt-4
  table.table.table-hover.table-bordered.border-black
    thead.table-dark
      th Count
      th Bdd
      th Existed records
    - cat_count.each_with_index do |r, index|
      tr
        - count, bdd  = r['count_result'].split(',')
        td= count
        td= bdd
        / td=

app/views/home/_possible_world_count_result.html.slim
.mt-4
  table.table.table-hover.table-bordered.border-black
    thead.table-dark
      th Count
      th Bdd
      th Existed records
    - cat_count.each_with_index do |r, index|
      tr
        td= r['count']
        td= r['sentence']
        td= r['ids']

app/views/home/_top_count_result.html.slim
.mt-4
  table.table.table-hover.table-bordered.border-black
    thead.table-dark
      th Count
      th Bdd
      th Prob
    - cat_count.each_with_index do |cat, index|
      tr
        td= cat['count']
        td= cat['sentence']
        td= cat['prob']

app/views/home/exact_count.js.erb
$('#exact .count-result').html('<%= j render("count_result", cat_count: @cat_count)%>')

app/views/home/hist_count.js.erb
$('#histogram .count-result').html('<%= j render("hist_count_result", cat_count: @cat_count)%>')

app/views/home/index.html.slim
h1.my-3 DuBio database 🐈 🐈
.row
  .col-2
    h4 Dictionary: #{@dict.name}
    - if @dict.rva.length > 0
      .mt-4
        table.table.table-hover.table-bordered.border-black
          thead.table-dark
            th= @dict.dict
          - @dict.rva.each_with_index do |pair, index|
            tr
              td= pair
  .col-5.pl-5
    h4.mb-4 Database Illustrations: Cat Breeds ##{pluralize(@cat_breeds.ntuples, 'cat')}
    = form_with url: cat_breed_create_path, method: :post do |form|
        .form-floating.mb-3
            = form.number_field :number_of_records, class: 'form-control'
            = form.label :number_of_records, "# of cats:"
        .row
          .col-4
            .form-floating.mb-3
                = form.number_field :number_of_random_variables, class: 'form-control'
                = form.label :number_of_random_variables, "# random variables:"
          .col-4
            .form-floating.mb-3
              = form.number_field :number_of_alternatives, class: 'form-control'
              = form.label :number_of_alternatives, "# alternatives per variable:"
          .col-4
            .form-floating.mb-3
                = form.number_field :arity_in_sentence, class: 'form-control'
                = form.label :arity_in_sentence, "# arity in sentence:"

        = form.submit "Clear & Generate", class: 'btn btn-dark'
    - if @cat_breeds.ntuples > 0
      .mt-4
        table.table.table-hover.table-bordered.border-black
          thead.table-dark
            th #
            th Cat
            th Breed
            th Sentence
            th Prob
          - @cat_breeds.each_with_index do |cat, index|
            tr
              td= cat['id']
              td= cat['name']
              td= cat['breed']
              td= cat['sentence']
              td= cat['prob']
  .col-5
    h4  Count
    ul#myTab.nav.nav-tabs role="tablist"
      li.nav-item role="presentation"
        button#exact-tab.nav-link.active aria-controls="exact" aria-selected="true" data-bs-target="#exact" data-bs-toggle="tab" role="tab" type="button" Exact
      li.nav-item role="presentation"
        button#histogram-tab.nav-link aria-controls="histogram" aria-selected="false" data-bs-target="#histogram" data-bs-toggle="tab" role="tab" type="button"  Histogram
      li.nav-item role="presentation"
        button#top-tab.nav-link aria-controls="top" aria-selected="false" data-bs-target="#top" data-bs-toggle="tab" role="tab" type="button"  Top
    #myTabContent.tab-content.mt-5
      #exact.tab-pane.fade.show.active aria-labelledby="home-tab" role="tabpanel"
        .bd-example
          = link_to 'COMB COUNT', home_exact_count_path, class: 'btn btn-dark remote-link', role: :button, remote: true
          = link_to 'PW COUNT', home_possible_world_count_agg_path, role: :button, class: 'btn btn-dark remote-link', remote: true
          = form_with url: home_top_count_path, method: :get, remote: true, class: 'd-inline-block' do |form|
            = form.submit "Top 5 count", class: 'btn btn-dark remote-link'
        .count-result
      / #histogram.tab-pane.fade aria-labelledby="profile-tab" role="tabpanel"
      /   = form_with url: home_hist_count_path, method: :get, remote: true, class: 'd-inline-block' do |form|
      /     .row.g-3.align-items-center
      /       .col-auto
      /         = form.label :bin, 'Number of bins'
      /       .col-auto
      /         = form.number_field :bin, value: 2, class: 'form-control'
      /       .col-auto
      /         = form.submit "Count", class: 'btn btn-dark d-inline-block remote-link'
      /   .count-result
      / #top.tab-pane.fade aria-labelledby="contact-tab" role="tabpanel"
      /   = form_with url: home_top_count_path, method: :get, remote: true, class: 'd-inline-block' do |form|
      /     .row.g-3.align-items-center
      /       .col-auto
      /         = form.label :k, 'Top k'
      /       .col-auto
      /         = form.number_field :k, value: 1, class: 'form-control'
      /       .col-auto
      /         = form.submit "Top count", class: 'btn btn-dark remote-link'
      /   .count-result


javascript:
  $('.remote-link').on('click', function() {
    debugger
    $(this).closest('.tab-pane').find('.count-result').html(
    ` <div class="mt-5" style="width: 50px; margin: 0 auto">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
      </div>
    `);
  })

app/views/home/possible_world_count.js.erb
$('#exact .count-result').html('<%= j render("possible_world_count_result", cat_count: @cat_count)%>')

app/views/home/possible_world_count_agg.js.erb
$('#exact .count-result').html('<%= j render("count_result", cat_count: @cat_count)%>')

app/views/home/top_count.js.erb
$('.count-result').html('<%= j render("count_result", cat_count: @cat_count)%>')