config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/exact_count'
  get 'home/possible_world_count'
  get 'home/possible_world_count_agg'
  get 'home/hist_count'
  get 'home/top_count'
  get 'home/algorithm'
  get 'algorithm/index'
  post 'algorithm/create'
  get 'algorithm/show'
  get 'algorithm/new'
  get 'experiment/index'
  get 'experiment/new'
  get 'experiment/show'
  get 'experiment/create'
  get 'experiment/a'
  get 'experiment/b'
  get 'experiment/c'
  get 'experiment/d'
  get 'experiment/e'
  get 'experiment/f'
  post 'dict/create'
  post 'cat_breed/create'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
  default_scope { order('id desc') }
  has_many :experiments, dependent: :destroy

  after_commit :run_experiment, on: [ :create, :update]

  def run_experiment
    HardWorker.perform_async(self.id)
  end
end

app/controllers/algorithm_controller.rb
class AlgorithmController < ApplicationController
  def index
  end

  def new
  end

  def create
    begin
      te = TestingEnvironment.new(params[:algorithm_name], params[:code])
      a = te.create_count_func
      algo = Algorithm.find_or_initialize_by(name: params[:algorithm_name])
      algo.code = params[:code]
      algo.type_of_count = params[:algorithm_type]
      algo.save
    rescue ActiveRecord::StatementInvalid => e
      @error = e.message
    end
  end

  def show
    @algorithm = Algorithm.find(params[:id])
  end
end

app/views/algorithm/create.js.erb
<% if !@error %>
  $('#algorithm-select').html('<%= j options_for_select(Algorithm.pluck(:name))%>');
  $('.algorithm-result').html('Create Algorithm successfully!').addClass('text-success').removeClass('text-danger');
<% else %>
  $('.algorithm-result').html('<%= j @error %>').addClass('text-danger').removeClass('text-success');
<% end %>

app/views/algorithm/index.html.slim
script language="javascript" src="https://codemirror.net/lib/codemirror.js" type="text/javascript"
script language="javascript" src="https://codemirror.net/mode/sql/sql.js" type="text/javascript"
link href="https://codemirror.net/lib/codemirror.css" rel="stylesheet" type="text/css" /
link href="https://codemirror.net/theme/lucario.css" rel="stylesheet" type="text/css" /

.container-xxl
  .row.my-3
    .col-auto
      h3 View Algorithm
    .col-auto.ml-3
      = link_to algorithm_new_path, class: 'btn btn-info' do
        span + Add New
  .row
    .col-3
      = select_tag :alogrithm, options_from_collection_for_select(Algorithm.all, 'id', 'name'), class: 'custom-select form-control mb-3'
  .row
    .col-12
      p.algorithm-code style="white-space: pre-wrap"
        = text_area_tag :current_code,  Algorithm.first&.code, class: 'form-control', rows: 25, value: Algorithm.first&.code

javascript:
  $('#alogrithm').on('change', function (argument) {
    id = $('#alogrithm').val()
    $.ajax({
      url: 'show?id='+id,
      method: 'GET'
    })
  })

  var editor = CodeMirror.fromTextArea(document.getElementById('current_code'), {
    lineNumbers: true,
    mode: 'text/x-plsql',
    theme: 'lucario',
    autoRefresh: true,
  });

  editor.setSize('100%', '70vh');

app/views/algorithm/new.html.slim
script language="javascript" src="https://codemirror.net/lib/codemirror.js" type="text/javascript"
script language="javascript" src="https://codemirror.net/mode/sql/sql.js" type="text/javascript"
link href="https://codemirror.net/lib/codemirror.css" rel="stylesheet" type="text/css" /
link href="https://codemirror.net/theme/lucario.css" rel="stylesheet" type="text/css" /
.container-xxl
  h3.my-3 Create Algorithm
  = form_with url: algorithm_create_path, method: :post, remote:true do |form|
    .row.mb-3
      .col-2
        = form.label :algorithm_name, "Name"
      .col-3
        = form.text_field :algorithm_name, class: 'form-control', placeholder: 'underscore_name'
      .col-7
        .row
          .col-2
            = form.label :algorithm_type, "Type", class: 'mx-4'
          .col-3
            = form.radio_button :algorithm_type, 'exact_count', class: 'mr-2'
            = form.label :algorithm_type, "Exact Count", value: 'exact_count', class: 'mx-2'
          .col-3
            = form.radio_button :algorithm_type, 'hist_count', class: 'mr-2'
            = form.label :algorithm_type, "Hist Count", value: 'hist_count', class: 'mx-2'
          .col-3
            = form.radio_button :algorithm_type, 'top_count', class: 'mr-2'
            = form.label :algorithm_type, "Top Count", value: 'top_count', class: 'mx-2'
    .row.mb-3
      .col-2
         = form.label :algorithm_name, "Code"
      .col-10
        = form.text_area :code, class: 'form-control', rows: 25
    .row
      .col-2
      .col-10
        .algorithm-result
    .row
      .col-2
      .col-10
        = form.submit "Create", class: 'btn btn-success'
javascript:
  var editor = CodeMirror.fromTextArea(document.getElementById('code'), {
    lineNumbers: true,
    mode: 'text/x-plsql',
    theme: 'lucario',
    autoRefresh: true,
  });

  editor.setSize('100%', '70vh');

app/views/algorithm/show.js.erb
editor.getDoc().setValue('<%= j @algorithm.code %>')