config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/exact_count'
  get 'home/possible_world_count'
  get 'home/possible_world_count_agg'
  get 'home/hist_count'
  get 'home/top_count'
  get 'home/algorithm'
  get 'algorithm/index'
  post 'algorithm/create'
  get 'algorithm/show'
  get 'algorithm/new'
  get 'experiment/index'
  get 'experiment/new'
  get 'experiment/show'
  get 'experiment/create'
  get 'experiment/a'
  get 'experiment/b'
  get 'experiment/c'
  get 'experiment/d'
  get 'experiment/e'
  get 'experiment/f'
  post 'dict/create'
  post 'cat_breed/create'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Dubio
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"
    link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"

  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        ul.nav.navbar-nav
          li.nav-item.active
            = link_to 'Database', home_index_path, class: 'nav-link'
          li.nav-item.active
            = link_to 'Experiments', experiment_index_path, class: 'nav-link'
          li.nav-item.active
            = link_to 'Algorithms', algorithm_index_path, class: 'nav-link'
    .container-fluid
      = yield
  footer
    .text-center
      a.pb-4.d-inline-block.text-dark href='https://ahriha.netlify.app/' Ha Le